### ISSUE TITLE
The referenced firmware bin file does not exist.

### ISSUE THREAD

**Issue by janikvonrotz** [Altitude-Tech/IOTBit_GSM#1]
https://github.com/Altitude-Tech/IOTBit_GSM/blob/f26fd4dc38283bd53b18c73599954bda46c7e691/IOTBit_GSM_Firmware_Updater/Firmware_Updater_IOTBit.py#L47

**Comment by Sam-AlteredCarbon** [comment]
Sorry that is just a typo it should be named IOTBitFirmware_GSM_V1.52.bin

**Comment by janikvonrotz** [comment]
I made PR and was also able to test it successfully.
